Switch twitter by bluesky for openmicroscopy.org
ome/www.openmicroscopy.org pull request #764
Opened 2024-12-12 17:52 UTC by jburel

Update link 
Icons will need to be reviewed

2025-01-20 10:37 UTC, pwalczysko commented on _includes/footer.html
> +                        <li><a href="https://bsky.app/profile/openmicroscopy.org" target="_blank"><i class="fa fa-fw fa-twitter"></i> Bluesky</a></li>
Remove ``fa-twitter`` at least from this line. I do not think we can publicize bluesky link with twitter icon...

2025-01-20 10:38 UTC, pwalczysko commented on on-the-web/index.html
> +                <h3 class="social-media-feature-section-headline"><i class="fa fa-twitter" aria-hidden="true"></i> Follow Us on Bluesky</h3>
Remove fa-twitter at least from this line. I do not think we can publicize bluesky link with twitter icon...

2025-01-20 10:38 UTC, pwalczysko commented on on-the-web/index.html
> +                        <a class="account-profile" href="https://bsky.app/profile/openmicroscopy.org" target="_blank"><img class="account-profile-pic" src="{{ site.baseurl }}/img/social-media/twitter
Remove twitter_ome.png

2025-01-20 10:39 UTC, pwalczysko requested changes
See my comments above - I do not think we should mislabel bluesky for twitter (i.e. do not publish twitter icons with bluesky

2025-01-20 10:48 UTC, jburel commented on on-the-web/index.html
> +                        <a class="account-profile" href="https://bsky.app/profile/openmicroscopy.org" target="_blank"><img class="account-profile-pic" src="{{ site.baseurl }}/img/social-media/twitter
This is just the name of the, there is no twitter logo

2025-01-20 11:02 UTC, pwalczysko commented on on-the-web/index.html
> +                <h3 class="social-media-feature-section-headline"><i class="fa fa-twitter" aria-hidden="true"></i> Follow Us on Bluesky</h3>
```suggestion
                <h3 class="social-media-feature-section-headline"><i class="fa fa-bluesky" aria-hidden="true"></i> Follow Us on Bluesky</h3>
```

2025-01-20 11:03 UTC, pwalczysko requested changes
I think this one https://github.com/ome/www.openmicroscopy.org/pull/764/files#r1922220863 should be amended too, this is in lines with the changes you have just done in the footer ?

2025-01-20 12:28 UTC, pwalczysko commented
![Screenshot 2025-01-20 at 12 28 04](https://github.com/user-attachments/assets/764e9c89-8852-45fd-8635-36dbaf3ab0f3)

2025-01-21 10:04 UTC, pwalczysko approved these changes
![Screenshot 2025-01-21 at 09 28 10](https://github.com/user-attachments/assets/2fa625ad-9da2-4f86-8cb2-48c1b54e673c)

2025-01-21 10:10 UTC, jburel commented
@sbesson @joshmoore @will-moore one of the changes in this PR is to use external fontawesome css (I have not deleted the one in this repo)

2025-01-21 10:17 UTC, sbesson commented
> one of the changes in this PR is to use external fontawesome css

:+1: Is the new style expected to be loaded from the CDN in production? Or should it be cached under https://github.com/ome/www.openmicroscopy.org/tree/master/css like previous FontAwesome and other styles used by the website?

2025-01-21 10:18 UTC, jburel commented
That is the question

2025-01-21 11:39 UTC, pwalczysko commented
> That is the question, what is the general view about using external vs internal

Sorry, obviously I have approved this PR. But thiking through the discussion here, I do not like the idea that icons on the prod www.op..py.org would vanish because external server X is down (we see similar problems with the linkchecker) and thus I would lean towards caching.

2025-01-21 14:51 UTC, joshmoore commented
Definitely no objections to pulling it in if we've done that in the past, I assume following https://docs.fontawesome.com/web/setup/host-yourself/webfonts

2025-01-22 09:02 UTC, jburel commented
https://snoopycrimecop.github.io/www.openmicroscopy.org/
Please check that no icons are missing on other pages

2025-01-22 11:47 UTC, pwalczysko commented
> https://snoopycrimecop.github.io/www.openmicroscopy.org/ Please check that no icons are missing on other pages

I went through all the pages manually on snoopy.
The icons are different (see example below), but working everywhere.

New icon
![Screenshot 2025-01-22 at 11 45 01](https://github.com/user-attachments/assets/fe4d13ff-3421-4965-b43f-bebfa5d7e19b)
Old icon
![Screenshot 2025-01-22 at 11 45 08](https://github.com/user-attachments/assets/854e8738-1628-42ca-b36c-d6b8a121b152)


But lgtm

2025-01-22 11:47 UTC, pwalczysko approved these changes

2025-01-22 16:09 UTC, pwalczysko commented
Happy for me to merge this and release ?

2025-01-22 16:26 UTC, jburel commented
Some icons have changed a bit but same theme
i think we should merge

2025-01-22 16:32 UTC, merged